In [22]:
def odd(x):
    for i in x:
        if i%2==0:
            pass
        else:
            print(i)
            
odd(range(1,30))
            

1
3
5
7
9
11
13
15
17
19
21
23
25
27
29


In [34]:
odd=[i*100 for i in range(10,30) if i%2!=0]
print (odd)

[1100, 1300, 1500, 1700, 1900, 2100, 2300, 2500, 2700, 2900]


### NUMPY
 Numerical python
 This introduces multidimensional arrays(ND Arrays) which are known as lists in python
 This adds new methods to manipulate arrays which are not in python lists
 Numpy also makes it easier to identify and work with null values

In [35]:
import numpy as np

In [36]:
import pandas as pd

In [168]:
ls=[[16,45,30,6,5],[6,None,8,70,8],[11,67,9,40,7]]

In [169]:
len(ls[::])

3

In [170]:
arr1=np.array(ls,)

In [171]:
arr2 = arr1.copy()

In [172]:
arr1

array([[16, 45, 30, 6, 5],
       [6, None, 8, 70, 8],
       [11, 67, 9, 40, 7]], dtype=object)

In [173]:
arr1.size

15

In [174]:
arr1.shape

(3, 5)

In [175]:
# changes all the array field to a float hence nan where there is None

In [204]:
arr1=np.array(ls,dtype=np.float) 

In [205]:
arr2 = arr1.copy()

In [206]:
#changing all nan to 0

In [207]:
arr1[np.isnan(arr1)] = 0


In [208]:
arr1

array([[16., 45., 30.,  6.,  5.],
       [ 6.,  0.,  8., 70.,  8.],
       [11., 67.,  9., 40.,  7.]])

In [209]:
#assign nan value as min array value

In [210]:
arr2

array([[16., 45., 30.,  6.,  5.],
       [ 6., nan,  8., 70.,  8.],
       [11., 67.,  9., 40.,  7.]])

In [211]:
arr2[np.isnan(arr2)]=arr2.mean()


In [214]:
arr2.mean()

nan

In [213]:
arr2

array([[16., 45., 30.,  6.,  5.],
       [ 6., nan,  8., 70.,  8.],
       [11., 67.,  9., 40.,  7.]])